export interface DialCode {
  name: string;
  code: string;
}

export const DIAL_CODES: DialCode[] = [
  { name: "Nigeria", code: "+234" },
  { name: "Ghana", code: "+233" },
  { name: "Kenya", code: "+254" },
  { name: "South Africa", code: "+27" },
  { name: "Egypt", code: "+20" },
  { name: "Ethiopia", code: "+251" },
  { name: "Tanzania", code: "+255" },
  { name: "Uganda", code: "+256" },
  { name: "Rwanda", code: "+250" },
  { name: "Senegal", code: "+221" },
  { name: "Ivory Coast", code: "+225" },
  { name: "Cameroon", code: "+237" },
  { name: "Morocco", code: "+212" },
  { name: "Algeria", code: "+213" },
  { name: "Tunisia", code: "+216" },
  { name: "Zambia", code: "+260" },
  { name: "Zimbabwe", code: "+263" },
  { name: "Botswana", code: "+267" },
  { name: "Namibia", code: "+264" },
  { name: "United States", code: "+1" },
  { name: "United Kingdom", code: "+44" },
  { name: "Canada", code: "+1" },
  { name: "France", code: "+33" },
  { name: "Germany", code: "+49" },
  { name: "Netherlands", code: "+31" },
  { name: "Spain", code: "+34" },
  { name: "Portugal", code: "+351" },
  { name: "Italy", code: "+39" },
  { name: "Ireland", code: "+353" },
  { name: "India", code: "+91" },
  { name: "China", code: "+86" },
  { name: "Japan", code: "+81" },
  { name: "Singapore", code: "+65" },
  { name: "United Arab Emirates", code: "+971" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "Brazil", code: "+55" },
  { name: "Mexico", code: "+52" },
  { name: "Australia", code: "+61" },
  { name: "New Zealand", code: "+64" },
];
